[package]
authors = ["CrazyMerlyn <crazy.d.merlyn@gmail.com>"]
name = "rlox"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
lazy_static = "1.5.0"

[dev-dependencies]
glob = "0.3.1"
